fix(ui): bulk edit subfields
payloadcms/payload pull request #10035
Opened 2024-12-18 03:40 UTC by jacobsfletch

Fixes #10019. Bulk editing subfields, such as a field within a group, does not currently work. This is because fields are flattened into options for the field selector, but then remain flattened when thread into `RenderFields`. Once received, `RenderFields` attempts to build up its own field paths, which are never correct because in order to build these field paths correctly, they must be thread through their parent's field. The fix is to separate the reduce logic for the field selector and the fields to render.

2025-02-07 15:05 UTC, mik01aj commented
Just came to say, thanks for your work in this PR, I'm looking forward to the fix ❤️

2025-03-19 20:12 UTC, paulpopus requested changes
Looks good to me, the e2e test should check that the array's and block's subfields render too to have better coverage

2025-03-19 20:52 UTC, paulpopus approved these changes

2025-03-19 20:54 UTC, jacobsfletch commented
> Looks good to me, the e2e test should check that the array's and block's subfields render too to have better coverage

Will address that in #11776

2025-03-19 21:01 UTC, merged