feat: add Estonian language support
payloadcms/payload pull request #10169
Opened 2024-12-25 11:04 UTC by tristankrass

2024-12-27 15:15 UTC, DanRibbens requested changes
This can't be merged until we resolve all the `undefined` values for `sl` translations.

2024-12-28 12:40 UTC, tristankrass commented
> This can't be merged until we resolve all the `undefined` values for `sl` translations.

@DanRibbens Added missing Slovenian translations.

2024-12-28 14:07 UTC, DanRibbens approved these changes

2024-12-28 14:44 UTC, DanRibbens requested changes
Looks like the build is still failing. 
https://github.com/payloadcms/payload/actions/runs/12526676553/job/34940626950#step:4:29

Are you able to build locally?

2024-12-28 15:33 UTC, tristankrass commented
> Looks like the build is still failing. [payloadcms/payload/actions/runs/12526676553/job/34940626950#step:4:29](https://github.com/payloadcms/payload/actions/runs/12526676553/job/34940626950#step:4:29)
> 
> Are you able to build locally?

```
Running pnpm run build:all yields following result: (Everything looks like it's working)


 Tasks:    32 successful, 32 total
Cached:    0 cached, 32 total
  Time:    1m20.397s 
```

2024-12-29 17:05 UTC, tristankrass commented
Any guidance, how to proceed?

2025-01-02 19:28 UTC, DanRibbens approved these changes
I had to add a few Estonian keys that have been added since your PR that were preventing the build from succeeding.
This should be ready to merge now. Thanks @tristankrass!

2025-01-02 19:41 UTC, merged