fix: updates syntax colors for light theme
payloadcms/payload pull request #1521
Opened 2022-11-28 16:27 UTC by JessChowdhury

## Description

Syntax colors are not suitable while using the Light theme - reported in [issue #1425](https://github.com/payloadcms/payload/issues/1425).

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Existing test suite passes locally with my changes - test suite used: **Fields**

Screenshot below shows the updated colors:
<img width="584" alt="Screen Shot 2022-11-28 at 4 26 22 PM" src="https://user-images.githubusercontent.com/67977755/204329562-3ee9ebc5-f566-47b3-a912-3e51b0984327.png">

2022-11-28 21:57 UTC, edtorba commented
It might be worth setting a different background colour too maybe? Even when in dark mode if the field is empty, you cannot tell where its boundaries start.

<img width="806" alt="Screenshot 2022-11-28 at 21 54 09" src="https://user-images.githubusercontent.com/2422019/204389123-cf202f2e-4bcd-4a33-a20f-f581623ba78a.png">
^ On the top field I have manually set `var(--theme-elevation-50)` as a background colour.

<img width="835" alt="Screenshot 2022-11-28 at 21 51 48" src="https://user-images.githubusercontent.com/2422019/204389331-5ebebf39-58a0-452a-98b4-4afd095b3730.png">
^ With some random code.

The same applies to the light theme.

2022-11-28 21:59 UTC, JarrodMFlesch commented
I agree @edtorba, we can do that before merging this in.

2022-11-29 10:51 UTC, JessChowdhury commented
@JarrodMFlesch I removed the theme provider and have added background / border to the input field (followed the same style as other fields).

@edtorba good call on the background - thank you!

<img width="1276" alt="Screen Shot 2022-11-29 at 10 46 56 AM" src="https://user-images.githubusercontent.com/67977755/204509863-2387c6fd-f956-4203-bb0e-ae02c98e93cb.png">
<img width="1277" alt="Screen Shot 2022-11-29 at 10 46 44 AM" src="https://user-images.githubusercontent.com/67977755/204509869-bc4bd52a-3ca1-41d9-8adf-7812cc0725ce.png">

2022-11-29 15:24 UTC, JarrodMFlesch requested changes

2022-11-29 15:24 UTC, JarrodMFlesch commented on src/admin/components/forms/field-types/Code/Code.tsx
> +import { useTheme } from '../../../utilities/Theme';
I believe this can be removed.

2022-11-29 15:24 UTC, JarrodMFlesch commented on src/admin/components/forms/field-types/Code/Code.tsx
> +        className="input"
Lets follow the current convention of using a `baseClass` and prepending that onto the elements className, see Array as an example here: https://github.com/payloadcms/payload/blob/master/src/admin/components/forms/field-types/Array/index.tsx#L31

2022-11-29 16:04 UTC, JessChowdhury commented
@JarrodMFlesch changes made

2022-11-29 16:13 UTC, JarrodMFlesch approved these changes

2022-11-29 16:14 UTC, merged