docs(example): adds virtual fields example
payloadcms/payload pull request #1990
Opened 2023-02-01 11:42 UTC by JessChowdhury

## Description

Adds virtual fields example.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [X] I have made corresponding changes to the documentation

2023-02-11 04:21 UTC, JarrodMFlesch requested changes
These comments are geared toward documentation and reducing friction when booting up the demo.

2023-02-11 04:21 UTC, JarrodMFlesch commented on examples/virtualFields/README.md
> +Copy the `.env.example` file in this directory to `.env`:
- [ ] `.env.example` is missing in this folder

2023-02-11 04:21 UTC, JarrodMFlesch commented on examples/virtualFields/README.md
> +
- [ ] If they used the seed script, what are the credentials? Lets list them here to reduce friction.

- [ ] Lets add the BeforeLogin component used in the [demo repo](https://github.com/payloadcms/public-demo/tree/master/src/components/BeforeLogin). You can conditionally render inside the component if `process.env.PAYLOAD_PUBLIC_SEED === "true"`

2023-02-11 04:21 UTC, JarrodMFlesch commented on examples/virtualFields/package.json
> +    "seed": "cross-env PAYLOAD_SEED=true PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon",
- [ ] Rename `PAYLOAD_SEED` to `PAYLOAD_PUBLIC_SEED`

2023-02-11 04:21 UTC, JarrodMFlesch commented on examples/virtualFields/src/server.ts
> +  if (process.env.PAYLOAD_SEED === 'true') {
- [ ] Rename `PAYLOAD_SEED` to `PAYLOAD_PUBLIC_SEED`

2023-02-16 12:10 UTC, JessChowdhury commented on examples/virtualFields/README.md
> +
I added some more on the collections to the next section 'Walkthrough' - might still need more detail let me know what you think.

2023-02-16 14:26 UTC, jacobsfletch commented
Should the directory structure be `examples/virtual-fields`? Instead of camel-cased.

2023-02-16 14:55 UTC, jacobsfletch commented on examples/virtual-fields/README.md
> +npx degit github:payloadcms/payload/examples/virtualFields
This path is now wrong.

2023-02-16 15:00 UTC, JessChowdhury commented on examples/virtual-fields/README.md
> +npx degit github:payloadcms/payload/examples/virtualFields
Fixed

2023-02-16 15:00 UTC, JessChowdhury commented on examples/virtual-fields/README.md
> +The following software is required:
Removed

2023-02-16 15:09 UTC, jacobsfletch commented on examples/virtual-fields/src/seed/index.ts
> +    payload.logger.info('Dropping database...');
No need to drop the db here, just add `PAYLOAD_DROP_DATABASE=true` to your dev script.

2023-02-16 15:10 UTC, jacobsfletch commented on examples/virtual-fields/src/server.ts
> +    await seed();
Add `payload.logger.info('---- SEEDING DATABASE ----')` just before this line.

2023-02-16 15:15 UTC, jacobsfletch approved these changes

2023-02-16 15:26 UTC, merged