fix: corrects keyboard accessibility for checkbox field
payloadcms/payload pull request #2025
Opened 2023-02-06 17:41 UTC by JessChowdhury

## Description

#2006 

Fixes double tab index on checkbox and adds focus highlight.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

https://user-images.githubusercontent.com/67977755/217045001-552e4d04-4463-4168-8840-814e0f8292d2.mov

https://user-images.githubusercontent.com/67977755/217045004-0b6ca045-0b75-4b89-8283-42b938b16282.mov

2023-02-06 20:49 UTC, JarrodMFlesch requested changes

2023-02-06 20:49 UTC, JarrodMFlesch commented on src/admin/components/forms/field-types/Checkbox/Input.tsx
> +        tabIndex={-1}
I believe you should just be able to use [aria-disabled](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled). Will need to test and verify.

2023-02-06 20:49 UTC, JarrodMFlesch commented on src/admin/components/forms/field-types/Checkbox/Input.tsx
> +        onFocus={() => setIsFocused(true)}
Buttons already have the ability to be targeted when they are focused, we should use the css `:focus` to style this.

2023-02-07 10:09 UTC, JessChowdhury commented
@JarrodMFlesch changes made!

2023-02-07 13:56 UTC, merged