fix: corrects position of select field dropdown in mobile drawer
payloadcms/payload pull request #2358
Opened 2023-03-20 13:25 UTC by JessChowdhury

## Description

#2355

Select dropdown was getting obscured by the bottom `save` banner. 

This change:

- Adjusts the drawer content wrap height so it ends at the banner instead of overlapping. 
- Conditionally renders the sidebar fields to prevent empty space in drawer on mobile.

- [X] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Existing test suite passes locally with my changes

2023-03-21 03:00 UTC, jacobsfletch commented
@JessChowdhury can you throw some screenshots up here?

2023-03-21 09:31 UTC, JessChowdhury commented
@jacobsfletch absolutely

Before:
https://user-images.githubusercontent.com/67977755/226565969-d3c29914-938e-4180-ae7d-94e04c8ca72d.mov

After:
https://user-images.githubusercontent.com/67977755/226566007-ef897ffb-b2ad-4a85-9d76-1123a757686e.mov

2023-03-21 13:13 UTC, jacobsfletch commented on src/admin/components/elements/Drawer/index.scss
> +      max-height: calc(100% - #{base(4)});
Instead of restricting height here we should just use bottom padding. This way the scroll container is still full height and feels more natural.

2023-03-21 13:14 UTC, jacobsfletch commented
I left one small bit of feedback l, but it also looks like CI is failing here too. Might need to look into that if they fail again.

2023-03-21 14:16 UTC, jacobsfletch commented on src/admin/components/elements/Drawer/index.scss
> +      max-height: calc(100% - #{base(4)});
There's some css way to achieve this, try a `::after` element with height or vertical padding.

2023-03-22 16:52 UTC, DanRibbens requested changes
This change makes it so the select dropdown is pushing content below it down. See recording: 

https://user-images.githubusercontent.com/6434612/226979188-96d6cd86-c4b4-4432-bf2d-db024e174f0c.mp4

2023-03-27 21:47 UTC, jmikrut commented
Hey @JessChowdhury — this ended up being a bit more complex, but I found that the `react-select` package has a `menuPlacement` option that you can set to `auto`, which handles this quite gracefully for us.

Gonna close this in preference to https://github.com/payloadcms/payload/commit/07eb8dd7d252043c00b79d532736896134204c4c.

2023-03-27 21:47 UTC, closed without merging