feat: supports collection compound indexes
payloadcms/payload pull request #2529
Opened 2023-04-20 09:18 UTC by yuanpli

## Description

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

2023-04-20 11:03 UTC, DanRibbens requested changes
This is awesome! I love it. I gave some feedback items. If you have time great, if not I'll go ahead and make the changes for the next release. Well done!

2023-04-20 11:03 UTC, DanRibbens commented on src/collections/config/types.ts
> +   * Custom collection indexes
This comment can probably be the same as the docs for better explanation.

2023-04-21 02:41 UTC, yuanpli commented on test/collections-index/int.spec.ts
Thanks for reviewing. I have made some changes according to your comments. Feel free to give me feedback.

2023-04-21 02:56 UTC, yuanpli commented on docs/configuration/collections.mdx
> +	indexes:[
Can you make this done before delivering this feature? Actually, I have no idea what example is better. In my opinion, the doc has a very clear explanation for this use case.

2023-04-22 17:46 UTC, ssyberg commented
Amazing, I was just about to add a feature request for this!

2023-04-25 04:01 UTC, DanRibbens approved these changes
I pushed a few changes to get this over the finish. Thank you so much for the PR!

2023-04-26 15:11 UTC, merged