feat: allow customizing the link fields
payloadcms/payload pull request #2559
Opened 2023-04-25 13:15 UTC by mvarendorff

## Description

This PR aims to support customizing the fields exposed and shown for Rich Text links (see #2167). I have implemented [this suggestion](https://github.com/payloadcms/payload/discussions/2167#discussioncomment-5197333) (I think).

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

2023-04-25 17:07 UTC, DanRibbens requested changes
I like the progress here and I think you touched everything you need for a basic use-case. I would like to see some changes before merging to eliminate breaking changes later as this evolves.

I would change the field function to take an args object: `{ defaultFields: Fields[], config: SanitizedConfig, i18n: Ii18n }`. 
where Ii18n is coming from ` import type { i18n as Ii18n } from 'i18next';`

This will make it possible to:
1) filter the collections offered as links in projects
2) internationalize the labels, placeholder texts, etc. in projects
3) add more args in the future without having breaking changes in Payload

2023-04-26 06:12 UTC, mvarendorff commented
That sounds reasonable, done!

2023-04-26 13:53 UTC, DanRibbens approved these changes

2023-04-26 15:08 UTC, merged

2023-05-26 12:57 UTC, MarvinVrdoljak commented
Hey there, thanks a lot for the approach. This is excactly what I was looking for. The only thing is, that my added custom fields are not getting saved anymore. For example, I want to replace the url field with custom one, that is validating the input for https/http. Moreover I'd like to extend the fields with a link-style-field: 

` {
      name: 'richTextContent', 
      type: 'richText',
      required: true,
      localized: true,
      admin: {
        link: {
          fields: ({defaultFields}) => {
            const theDefaultFields = defaultFields.filter((field) => (field as any).name != 'url')
            const urlField = defaultFields.find((field) => (field as any).name === 'url')
            return [
              ...theDefaultFields,
              {
                name: 'url',
                type: 'text',
                required: true,
                admin: {condition: urlField?.admin?.condition, placeholder: 'https://'},
                validate: (val, options) => {
                  const errorText = options?.t('fieldValidation:invalidUrl')
                    ? options.t('fieldValidation:invalidUrl')
                    : 'Error'
                  const valid = /^(http|https):\/\/[^ "]+$/.test(val)
                  if (valid) {
                    return true
                  }
                  return errorText
                },
              },
              {
                name: 'style',
                label: 'Link Style',
                type: 'select',
                options: ['button', 'icon-link'],
              },
            ]
          },
        },
      },
    }`

Every Field will be shown correctly:
![Screenshot 2023-05-26 145410](https://github.com/payloadcms/payload/assets/25500828/ee34aa67-fa79-4156-95e1-c793499bb166)

The only problem I have now is that as soon as I submit the link, my "link style" won't be saved. I tried it with other field types and field names - it's just not working. The new url field is working perfectly (guess because of the same name as the field before: "url") as well as the other default fields. Guess there is a problem with the payload state?