Refactor imageResizer.ts to allow for keeping original size in certain cases
payloadcms/payload pull request #2574
Opened 2023-04-27 17:50 UTC by angelobartolome

## Description

- [ ] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2023-05-04 14:44 UTC, angelobartolome commented
@DanRibbens friendly ping on this

2023-05-08 16:17 UTC, denolfe requested changes
I think this is a good thing to have. However, I don't see a need for a new property to accomplish this since Sharp can handle `undefined` for the `height` and `width` properties.

Let's get rid of the additional property and handle the scenario where both `height` and `width` are `undefined` on `needsResize` with `(!desiredSize.height && !desiredSize.width)`.

I briefly tested this out, and it appeared to work as expected.

2023-05-09 20:02 UTC, angelobartolome commented
Added a couple of tests + applied suggestion to not add a new property @denolfe

2023-05-10 12:43 UTC, denolfe approved these changes

2023-05-10 12:44 UTC, denolfe commented
Looks great, @angelobartolome !

2023-05-10 12:44 UTC, merged