Feature/expose graphql types
payloadcms/payload pull request #2610
Opened 2023-05-03 07:16 UTC by paulpopus

## Description

Related to https://github.com/payloadcms/payload/issues/2557 , I will update the documentation around GraphQL after this PR in case there are any further changes needed in this code.

This PR exports:
- buildPaginatedListType
- the internally used GraphQL library and type to make sure there's no conflicts (happy to revert on this one but I thought it might make the DX easier)
- the mutations and queries type into a re-usable type `GraphQLExtension` in the config

And it attaches the created `buildPaginatedType` from collections to the available types for re-use on `payload.collections.graphQL.`

- [x] I have read and understand the CONTRIBUTING.md document in this repository

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update (will come in a PR after this one)

2023-05-08 16:37 UTC, denolfe requested changes
Just some formatting tweaks. Other than that looks good. 

Will re-review when docs are added 👍

2023-05-08 16:37 UTC, denolfe commented on graphql.d.ts
> +export {default as GraphQL} from 'graphql';
Let's clean up the spacing and quote type here.

2023-05-08 16:37 UTC, denolfe commented on src/collections/graphql/init.ts
> +      singularName
Add back comma

2023-05-08 16:37 UTC, denolfe commented on graphql.js
> +exports.GraphQL = require("graphql");
Discussed this with the team, we're okay with this 👍

2023-05-10 12:21 UTC, paulpopus commented
@denolfe I've fixed those code style issues. Added documentation, let me know how it looks.

Going through it again, there's probably another round of work to do to make working with GraphQL feel more first class.

2023-05-10 12:53 UTC, denolfe approved these changes

2023-05-10 12:53 UTC, merged