fix: handle invalid tokens in refresh token operation
payloadcms/payload pull request #3647
Opened 2023-10-13 20:08 UTC by diesieben07

## Description

Fixes the "refresh token" operation to correctly reject invalid tokens instead of crashing with an internal server error.
Fixes #3646 

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes

2023-10-27 16:09 UTC, denolfe requested changes
Just one minor change, then this should be good!

2023-10-27 16:09 UTC, denolfe commented on packages/payload/src/auth/operations/refresh.ts
> +  if (typeof args.token !== 'string' || args.req.user == null) throw new Forbidden(args.req.t)
I think something to handle all falsy values would be better. Something like `|| !args.req.user`

2023-10-28 09:08 UTC, diesieben07 commented
I don't know why the tests failed. It does not seem related to my changes.

2023-11-07 15:01 UTC, denolfe approved these changes

2023-11-07 17:03 UTC, denolfe commented
@diesieben07 I think the CI issue has been fixed on latest. Can you rebase latest main? Looking to merge this after CI passes.

2023-11-07 17:16 UTC, diesieben07 commented
@denolfe Done, looks like all tests succeeded now.

2023-11-07 19:55 UTC, merged

2023-11-07 19:55 UTC, denolfe commented
@diesieben07 Thanks! 👍