chore: imports admin bar
payloadcms/payload pull request #3684
Opened 2023-10-16 13:30 UTC by jacobsfletch

## Description

Imports https://github.com/payloadcms/payload-admin-bar into monorepo.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Chore (non-breaking change which does not add functionality)

## Checklist:

- [x] Existing test suite passes locally with my changes

2024-05-01 20:18 UTC, denolfe requested changes
Do we plan on supporting this plugin for 3.0?

If so, we need to get this building, and we can get it imported.

2024-05-10 15:41 UTC, jacobsfletch commented
This isn't a plugin, it's a standalone pkg. This _is_ something we will want to continue to maintain. I'll see about updating this PR.

2025-03-05 17:40 UTC, denolfe approved these changes
Looks good. A screenshot in the PR description would be nice, as many likely have not seen this 👍

2025-03-05 18:02 UTC, denolfe commented
Looks like the normal build flow was somehow skipped. Should figure that out before merging.

2025-03-05 19:14 UTC, merged