Fix generate:types bug #3697
payloadcms/payload pull request #3698
Opened 2023-10-16 17:56 UTC by xHomu

## Description

generateEntityDeclarations function creates mismatched type names. We'll simply use the existing Config type instead.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Existing test suite passes locally with my changes

2023-10-17 21:03 UTC, denolfe commented
Will validate this tomorrow.

2023-10-18 16:14 UTC, denolfe commented
Just published a beta to test this. The typing is working as expected.

2023-10-18 16:25 UTC, denolfe requested changes
Just some small things. This looks to be functioning as expected, though.

2023-10-18 16:25 UTC, denolfe commented on packages/payload/src/bin/generateTypes.ts
> +  const declare = `declare module "payload" {\n  export interface GeneratedTypes extends Config {} \n}`
Small nitpick: remove the space between `{}` and `\n`. This equates to trimming whitespace on the generated file.

2023-10-18 16:25 UTC, denolfe commented on packages/payload/src/bin/generateTypes.ts
>  import { toWords } from '../utilities/formatLabels'
Clean up any unused imports.

2023-10-18 23:31 UTC, xHomu commented
Thanks for the code review!

2023-10-19 15:36 UTC, merged

2023-10-19 15:36 UTC, denolfe commented
Thanks for the PR @xHomu !