chore: adds handling for long field error messages
payloadcms/payload pull request #3812
Opened 2023-10-23 01:27 UTC by PatrikKozak

## Description

Adds handling for longer field error messages.

![Screen Shot 2023-10-22 at 9 21 40 PM](https://github.com/payloadcms/payload/assets/35232443/05bcea4b-d0bb-450a-ad61-3bfc96aa9b30)

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Chore (non-breaking change which does not add functionality)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] Existing test suite passes locally with my changes

2023-10-27 12:51 UTC, JarrodMFlesch commented
@PatrikKozak I think this still needs some work right? We are just going to throw the error message above the input for now.

2023-10-27 16:17 UTC, PatrikKozak commented
@JarrodMFlesch Yeah this still needs some work - I don't think putting the message above the field is the right move either though.

2023-11-02 12:51 UTC, JarrodMFlesch requested changes

2023-11-02 12:51 UTC, JarrodMFlesch commented on packages/payload/src/admin/components/forms/field-types/Text/Input.tsx
> +      {showError && <Error message={errorMessage} showError={showError} />}
I believe Error handles showing/not-showing internally.

2023-11-02 12:51 UTC, JarrodMFlesch commented on packages/payload/src/admin/components/elements/Tooltip/index.tsx
> +          .join(' ')}
Im not sure all of your changes are necessary because this is aria-hidden.

2023-11-02 12:51 UTC, JarrodMFlesch commented on packages/payload/src/admin/components/elements/Tooltip/index.tsx
> +          messageIsLong ? 'tooltip--position-stretch-top' : `tooltip--position-${position}`,
Let me know when you want to boot this up and we can take a look visually together 👍

2023-11-02 16:35 UTC, PatrikKozak commented
@DanRibbens Jarrod and I made an update to `checkbox` validation [here](https://github.com/payloadcms/payload/pull/3812/files#diff-64ef6752d148ff573e45c996082e7a299ef5d29e689655e64d96c1955098f42e) in this PR.

We think this is likely more the intended result when using the `required` property on a checkbox. People can then just write their own validation if they wanted to.

Let us know what you think.

2023-11-02 18:59 UTC, JarrodMFlesch commented on packages/payload/src/fields/validations.ts
> +  if (required && !value) return t('validation:required')
I reverted this change.

2023-11-03 14:40 UTC, merged