fix: fixes transactionID isolation for GraphQL
payloadcms/payload pull request #4095
Opened 2023-11-10 13:35 UTC by diesieben07

## Description

Fixes #4091 by using a JavaScript Proxy to isolate the `transactionID` between individual GraphQL operations instead of copying the request.
I have also fixed the missing cloning of the request for the `collections/findByID` resolver.

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Existing test suite passes locally with my changes

2023-11-10 15:41 UTC, DanRibbens requested changes
If you do a search for `req: { ...context.req } as PayloadRequest` you'll find a few more places where I did this which your PR should also replace.

2023-11-10 15:41 UTC, DanRibbens commented on packages/payload/src/utilities/isolateTransactionID.ts
> +export default function isolateTransactionID(req: PayloadRequest): PayloadRequest {
I was looking for a way to do this and couldn't find it. Great work!

2023-11-10 16:13 UTC, diesieben07 commented
@DanRibbens Right, of course :man_facepalming: I've now gone through `registerSchema` and checked every resolver.

Should we expose `isolateTransactionID` for people to use in custom GraphQL resolvers or maybe we should handle it transparently by wrapping any custom resolver with it? The latter sounds more convenient for users and makes it impossible to forget.

2023-11-11 00:04 UTC, DanRibbens commented
> Should we expose `isolateTransactionID` for people to use in custom GraphQL resolvers or maybe we should handle it transparently by wrapping any custom resolver with it? The latter sounds more convenient for users and makes it impossible to forget.

We never want people to have to learn these kinds of ugly details if it can be avoided. I haven't reviewed this yet but it sounds like we need to handle it.

Thanks!

2023-11-11 12:49 UTC, diesieben07 commented
I have now added a wrapper to any (top level) resolver in the custom mutations and queries. I've added a test that makes sure they are using separate transaction IDs.

2023-11-14 21:06 UTC, DanRibbens approved these changes

2023-11-14 21:07 UTC, merged