next should not handle /admin/* routes
payloadcms/payload pull request #4152
Opened 2023-11-15 10:16 UTC by abernier

## Description

- [ ] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](../templates/) directory (does not affect core functionality)
- [ ] Change to the [examples](../examples/) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2023-11-15 18:17 UTC, jacobsfletch commented
@abernier is this change necessary? What problems are you experiencing? Payload is attaching admin route handlers to the shared Express server. Is this to prevent you from adding a `/admin` route in your Next app?

2023-11-15 19:10 UTC, jacobsfletch commented
Following up here, I think that it may be _more_ confusing for a developer to add an admin route to their Next app and have it be ignored by the server. They probably would expect that either case is handled, even if their route happens to override an existing Payload route (this might even be their desired behavior). For example, let's say they wanted to add `/admin/my-custom-view`—currently, they have the ability to either do it from the Payload config _or_ with Next.js, which might be a good thing.

2023-11-19 08:19 UTC, abernier commented
I added this to prevent my Next app (which has a [[...catchall]] route) catching a webpack related route

2023-11-27 22:37 UTC, jacobsfletch commented
Ok that makes more sense now, thanks for follow-up 👍

2024-05-01 20:58 UTC, denolfe requested changes
Can you provide an example of a route that is not working for you?

2024-05-01 21:01 UTC, denolfe commented
We'll be reworking all of the examples for 3.0.

2024-05-01 21:01 UTC, closed without merging