fix(db-postgres): relationship fields: ilike used for contains operations
payloadcms/payload pull request #4212
Opened 2023-11-19 12:54 UTC by AlessioGr

## Description

- [ ] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](../templates/) directory (does not affect core functionality)
- [ ] Change to the [examples](../examples/) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2023-11-20 19:03 UTC, DanRibbens commented on packages/db-postgres/src/queries/parseParams.ts
> +                  operator = 'equals'
We can't just assume they want an `equals` operator. This wouldn't work if you were querying with `exists`, `in`, or `like`.

2024-01-21 01:13 UTC, DanRibbens requested changes
Looks good

2024-01-21 01:13 UTC, DanRibbens commented on test/relationships/int.spec.ts
> +        console.log('VALID PARENTS', validParents)
Delete

2024-02-06 21:50 UTC, denolfe commented
@DanRibbens @AlessioGr Should this be revisited?

2024-03-26 18:35 UTC, DanRibbens approved these changes

2024-04-05 17:59 UTC, merged