fix: allow for nested block fields to be queried
payloadcms/payload pull request #4237
Opened 2023-11-21 21:38 UTC by JarrodMFlesch

## Description

Fixes a bug where search params were being validated, but fieldAccess was incorrectly accessing properties that do not exist for block fields and throwing an error. This safely sets field access based on the top level block.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2023-11-21 21:48 UTC, DanRibbens requested changes
It would be nice to have a test case for this. There is so much complexity when it comes to querying that the only way to maintain it is with tests.

2023-11-29 16:03 UTC, DanRibbens approved these changes

2023-11-29 16:03 UTC, merged

2023-12-05 02:56 UTC, ficeco commented
Would this work for querying relationship fields inside blocks?

2023-12-05 03:15 UTC, DanRibbens commented
> Would this work for querying relationship fields inside blocks?

@ficeco this should be possible though I'm unsure if this PR changed that or not. Are you having trouble? You should open a new issue if so.

2023-12-06 15:42 UTC, ficeco commented
I had opened [this issue](https://github.com/payloadcms/payload/issues/4008) and I'm having the same issue after updating Payload and db-postgres.