Allow user to have custom options while using `payload.update` operation
payloadcms/payload pull request #4369
Opened 2023-12-04 07:33 UTC by WilsonLe

## Allow user to provide custom options when using update operations

This PR allows user to provide custom options when using payload.update(...). The custom `options` is optional and therefore won't break anything existing code. The custom options allow user to further leverage database ORMs and ODMs. This PR specifically changes mongoose database adapter such that user can leverage the `upsert` option when using `findOneAndUpdate` operation.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

2024-12-06 14:41 UTC, DanRibbens commented
This is a good feature idea. I added similar for v3 but only at the db adapter method level. It would really help us if you wanted to make the same PR to `main` so it can get into v3 going foward.

What do you think @WilsonLe?

2024-12-06 14:52 UTC, WilsonLe commented
I'll resolve all the conflicts over weekends. Thank you for getting back to my PR 😅

2024-12-10 20:54 UTC, WilsonLe commented
After merging with main, it seems like this has been implemented. However, why didn't we accept the `options` parameter in `payload.update` and forward it to `payload.db.updateOne`? Or was the `options` parameter is already forwarded and I just didn't see it?

2026-04-02 14:40 UTC, DanRibbens requested changes
This won't be merged as it is. We'd need to implement the types using the declare module on the db adapters that support this.

2026-04-02 14:40 UTC, DanRibbens commented on packages/payload/src/collections/operations/update.ts
> +  options?: Record<string, unknown>
We would want to extend the types for the db adapter using the declare module pattern. See example: https://github.com/payloadcms/payload/blob/92da9faade16b2e055a78b0f356a3473ca6ec5eb/packages/db-mongodb/src/index.ts#L252

2026-04-02 14:41 UTC, DanRibbens commented
Closing due to age of PR and conflicts. If this feature is important to you, we can discuss it and open another PR.

2026-04-02 14:41 UTC, closed without merging