Rtl
payloadcms/payload pull request #4684
Opened 2024-01-04 09:03 UTC by DasMergo

## Description

- [ ] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2024-01-04 14:40 UTC, DanRibbens requested changes
Thanks for maintaining the RTL support for the admin UI. Can you fix the header scss?

2024-01-04 14:40 UTC, DanRibbens commented on packages/payload/src/admin/components/elements/Header/index.scss
> +
It looks like this was removed by accident maybe?
```
ERROR in ./packages/payload/src/admin/components/elements/Header/index.scss (./node_modules/.pnpm/css-loader@5.2.7_webpack@5.88.2/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/.pnpm/postcss-loader@6.2.1_postcss@8.4.31_webpack@5.88.2/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/.pnpm/sass-loader@12.6.0_sass@1.69.4_webpack@5.88.2/node_modules/sass-loader/dist/cjs.js!./packages/payload/src/admin/components/elements/Header/index.scss)
Module build failed (from ./node_modules/.pnpm/sass-loader@12.6.0_sass@1.69.4_webpack@5.88.2/node_modules/sass-loader/dist/cjs.js):
SassError: expected "}".
    ╷
192 │ }
    │  ^
    ╵
  packages/payload/src/admin/components/elements/Header/index.scss 192:2  root stylesheet
```

2024-01-04 19:04 UTC, DasMergo reviewed
fixed

2024-01-05 02:40 UTC, DanRibbens approved these changes
Thanks!

2024-01-05 02:45 UTC, merged