Example/hierarchy
payloadcms/payload pull request #4923
Opened 2024-01-25 17:56 UTC by kendelljoseph

## Description

This adds a hierarchy example that demonstrates the capability to create a hierarchy between `entities` and `people`.

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)

## Checklist:

- [x] Existing test suite passes locally with my changes
- [x] I have made corresponding changes to the documentation

2024-01-25 18:05 UTC, DanRibbens approved these changes

2024-01-26 15:10 UTC, jacobsfletch requested changes
The README needs to include a high-level description about _what_ the example is demonstrating, in a 2-3 concise sentences. It also needs to include a "How it works" section that outlines the setup and all hooks, etc that are used to achieve its core functionality.

2024-01-26 20:47 UTC, jacobsfletch commented on examples/hierarchy/README.md
> +A hierarchy for [Payload](https://github.com/payloadcms/payload).
```suggestion
This example demonstrates how to achieve a virtual hierarchy between documents in your [Payload](https://github.com/payloadcms/payload) application.```

2024-01-26 20:48 UTC, jacobsfletch commented on examples/hierarchy/README.md
> +This repo was created by running `npx create-payload-app@latest` and selecting the "blank" template then it was modified.
```suggestion
```

2024-01-26 20:48 UTC, jacobsfletch commented on examples/hierarchy/README.md
> +See the official [Examples Directory](https://github.com/payloadcms/payload/tree/main/examples) for details on how to use Payload in a variety of different ways.
```suggestion
```

2024-01-26 20:55 UTC, jacobsfletch commented on examples/hierarchy/README.md
> +This is an example parent-child hierarchy between Entities and People.  Entities use of a virtual field to find people and entities it is related to.
This example achieves parent/child relationships between your documents through the use of virtual fields. When you query a document with the `?children=true` query param, an `afterRead` hook is used to populate the documents within its own tree.

For more information on how virtual fields, see the [Official Virtual Fields Example]([Virtual Fields](https://github.com/payloadcms/payload/tree/main/examples/virtual-fields).

2024-01-26 21:16 UTC, jacobsfletch approved these changes

2024-01-26 21:17 UTC, merged