feat(plugin-seo): add pt-br translations
payloadcms/payload pull request #5269
Opened 2024-03-08 15:34 UTC by WillFelisberto

## Description

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2024-03-10 05:10 UTC, AlessioGr requested changes

2024-03-10 05:10 UTC, AlessioGr commented on packages/plugin-seo/src/translations/pt-br.json
> +		"previewDescription": "Exact result listings may vary based on content and search relevancy."
Could you translate this key too?

2024-03-11 12:13 UTC, WillFelisberto commented on packages/plugin-seo/src/translations/pt-br.json
> +		"previewDescription": "Exact result listings may vary based on content and search relevancy."
Sorry, I fixed that.

2024-03-26 12:35 UTC, WillFelisberto commented
@jacobsfletch @AlessioGr  Please don't forget me 😅

2024-05-30 17:11 UTC, denolfe approved these changes

2024-05-30 17:12 UTC, denolfe requested changes
Looks like this failed some e2e tests

2025-05-05 20:52 UTC, closed without merging