fix(ui): update relationship cell formatted value when when search changes
payloadcms/payload pull request #6208
Opened 2024-05-04 04:16 UTC by r1tsuu

## Description

Fixes https://github.com/payloadcms/payload-3.0-demo/issues/181
Although issue is about page changing, it happens as well when you change sort / limit / where filter

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Existing test suite passes locally with my changes

2024-05-07 13:24 UTC, jacobsfletch commented on packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
> +        setHasRequested(false)
I see what you're doing here and I think this approach is generally right, but this logic feels more like it belongs in its own `useEffect` with `searchParams` as its only dependency. Are you comparing old params bc its an object and therefore _new_ on every render? I'm my mind it looks something like this:

```tsx
  useEffect(() => {
    if (hasRequested) {
      setHasRequested(false)
    }
  }, [searchParams, hasRequested])
```

^ this might not work as is, just a POC.

2024-05-07 14:34 UTC, r1tsuu commented on packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
> +        setHasRequested(false)
> I see what you're doing here and I think this approach is generally right, but this logic feels more like it belongs in its own `useEffect` with `searchParams` as its only dependency. Are you comparing old params bc its an object and therefore _new_ on every render? I'm my mind it looks something like this:
> 
> ```tsx
>   useEffect(() => {
>     if (hasRequested) {
>       setHasRequested(false)
>     }
>   }, [searchParams, hasRequested])
> ```
> 
> ^ this might not work as is, just a POC.

Seems like additional `useEffect` leads to infinity `useEffect`'s call.
<img width="987" alt="image" src="https://github.com/payloadcms/payload/assets/64744993/e19ca17a-eb22-4830-b013-aff697536d9c">

2024-05-07 14:36 UTC, r1tsuu commented on packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
> +        setHasRequested(false)
that's why i decided to put it into current `useEffect` so we can be sure that we aren't updating state in loop

2024-05-07 14:57 UTC, JessChowdhury commented on packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
> +        setHasRequested(false)
We can separate this logic into it's own `useEffect` and prevent an infinite loop if we check `searchParams` against the previous (as you were doing before). I'm going to make this change - you can see what I mean in the next commit.

2024-05-07 15:03 UTC, r1tsuu commented on packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
> +        setHasRequested(false)
Oh, yeah that makes sense

2024-05-07 15:03 UTC, jacobsfletch commented on packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
> +  const [memoizedSearchParams, setMemoizedSearchParams] = useState(searchParams)
`useRef` is more efficient than this because it does not trigger a re-render of the entire component

2024-05-07 15:08 UTC, jacobsfletch commented on packages/ui/src/elements/Table/DefaultCell/fields/Relationship/index.tsx
> +        setHasRequested(false)
The more I think about this, I don't think tying to `searchParams` is the right approach altogether. Because although this would _work_ it would cause necessary requests. For example, if the search input changes as you type, but the results stay the same, requests are still made. Instead, what we need to do is "watch" the _values_ of the cells themselves, and determine if we need to refetch any based on whether of not their relationship IDs have actually changed.

2024-05-07 15:11 UTC, jacobsfletch commented
This needs a test as well, elsewhere in our e2e test suites (probably Live Preview) Playwright is able to "watch" the network requests being made. That's what we need to do here for two tests at least, 1. to test that changing results (i.e. a new page) triggers new network requests (and updates the cell's HTML), and 2. to test that changing params _but not results_ does _not_ trigger a network request.

2024-05-07 17:04 UTC, r1tsuu commented
Sorry, i could be wrong, but did you guys also consider to populate these server side, since we anyway are retrieving docs in the server component? We still want `depth: 0` of course, but populate manually with our `dataLoader` user's selected relationship columns /  top level relations.

that's also debatable by UX i think, some people prefer this lazy loading thing and some don't want to see that something is still loading but don't might if the request would took a little bit longer.

But of course if a bottleneck here is huge, then i'm totally wrong.

2024-05-08 14:45 UTC, JessChowdhury commented
> 1. to test that changing results (i.e. a new page) triggers new network requests (and updates the cell's HTML), and 2. to test that changing params but not results does not trigger a network request.

@jacobsfletch I've added the first test - for `2.` when you say changing the params but not the results, what do you mean?

2024-05-20 19:42 UTC, jmikrut commented
> Sorry, i could be wrong, but did you guys also consider to populate these server side, since we anyway are retrieving docs in the server component?

Hey @r1tsuu yep in a much earlier version of Payload we did indeed load all relations via the dataloader, but the problem was when you have long pages with many rows on the screen at once (100+). The response was just huge. 

Keeping the initial load down as tiny as possible makes sure that the initial load is speedy all the time, and then we can lazy-load relations when they scroll onto the screen. But it's a good thought!

I think this PR is good to go at this point, right? @jacobsfletch you wanna merge and we can get it out in a new beta?

Thank you everyone!

2024-05-20 19:45 UTC, jacobsfletch approved these changes

2024-05-20 20:00 UTC, jacobsfletch requested changes
Looks like this is actually causing some failing tests related to recursive dependencies. Will need to fix this before merging.

2024-05-20 20:03 UTC, merged

2024-05-20 20:03 UTC, jmikrut commented
i'm on the fix for that right now - thanks for the help here everyone!

2024-05-21 02:01 UTC, r1tsuu commented
Thanks @jacobsfletch @JessChowdhury for carrying here and @jmikrut for bumping this!