fix: error 431 when having a lot of relationship items
payloadcms/payload pull request #6487
Opened 2024-05-24 09:00 UTC by andershermansen

## Description

To fix the issue of GET request getting a too long query variable as described in #6486, I have implemented X-HTTP-Method-Override header to allow this query to be sent as a POST request and giving the information that is it actually a GET request.

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] Existing test suite passes locally with my changes

2024-05-24 12:31 UTC, JarrodMFlesch commented
@andershermansen would you mind creating a test that tests for this?

It would need to be done under `test/fields-relationship/e2e.spec.ts`. I think it would be relatively simple.

## Generate data with SDK
1. Use the `payload` SDK client present in that file to create many items for a relatable collection, i.e. many `relation-one` docs
2. Then use the SDK to create a doc for the `fields-relationship` collection and set the all the ID's (except for 1, save it for later!) created in step 1 to the `relationshipHasMany` field within it.

## Use Playwright to test
1. Then use Playwright to attempt to add that remaining relationship doc
2. Ensure that the doc can be added successfully

The test should fail without your change and pass with it. If you can do this that would be very helpful! Let me know what you think.

2024-06-03 06:14 UTC, andershermansen commented
@JarrodMFlesch A friendly reminder about this fix. If you want the fix or the test done in a different way, let me know and I can work on it.

2024-06-10 17:35 UTC, DanRibbens requested changes
This is a good solution. I would like this to be a documented feature in our docs. I would add it to this page: https://payloadcms.com/docs/rest-api/overview

2024-06-11 06:17 UTC, andershermansen commented
@DanRibbens Thanks. I have created and pushed docs as well.

2024-06-13 19:14 UTC, andershermansen commented
I see you already adjusted it. Good change.

2024-06-13 19:18 UTC, JarrodMFlesch commented
@andershermansen I did, I want to merge it in and close your issue 👼

2024-06-13 19:27 UTC, merged

2024-07-15 07:32 UTC, NiklasSchmidts commented
Hi,
quick question, is this also planned to be fixed in version 2. ?