fix(email-nodemailer): Fix skipVerify behaviour being reversed
payloadcms/payload pull request #6790
Opened 2024-06-15 10:31 UTC by JasperBeaurain

## Description
Fixes #6789

The skipVerify field in NodemailerAdapterArgs worked in reverse of what it was supposed to do:
- With skipVerify = true -> Verified transport
- With skipVerify = false -> Did not verify transport

This PR makes the property work in the intended way:
- With skipVerify = true -> DO NOT verify transport
- With skipVerify = false -> DO verify transport

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2024-06-17 17:25 UTC, denolfe requested changes
@JasperBeaurain Thanks for the PR! Just one additional scenario that needs to be handled.

2024-06-17 17:25 UTC, denolfe commented on packages/email-nodemailer/src/index.ts
> +  if (emailConfig.skipVerify === false) {
This also needs to handle when `skipVerify` is undefined. It should verify when undefined.

2024-06-17 20:03 UTC, JasperBeaurain commented
@denolfe Whoops, I missed that indeed. Made changes as requested.
I also added a few tests that validate the flag's behaviour.

2024-07-15 16:52 UTC, merged

2024-07-15 16:52 UTC, denolfe commented
Thanks for the PR @JasperBeaurain ! Love that you added tests 🙏