feat(ui): show nested fields in groups as separate columns in table
payloadcms/payload pull request #7355
Opened 2024-07-25 13:29 UTC by andershermansen

## Description

Group fields are shown as one column, this PR changes this so that the individual field is now shown separatly.

Before change:
<img width="1227" alt="before change" src="https://github.com/user-attachments/assets/dfae58fd-8ad2-4329-84fd-ed1d4eb20854">

After change:
<img width="1229" alt="after change" src="https://github.com/user-attachments/assets/d4fd78bb-c474-436e-a0f5-cac4638b91a4">

- [X] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2024-07-25 13:38 UTC, andershermansen commented
@JarrodMFlesch Ref the comment you made in #7331, that this was not for now. I wanted to work more on it.
Please let me know what you think about the approach, if it's fine I will work further on checking any side effects and work on tests to ensure it will be covered and look at any failing test.

I also wanted to know what you think about the column header/label. In filters this has a > for nested fileds. Like this:
<img width="1227" alt="Skjermbilde 2024-07-25 kl  15 35 17" src="https://github.com/user-attachments/assets/8d6f0e69-27ac-4c8a-8318-26309b050cc0">
I think that should also apply to the column header. What do you think?

2024-07-25 13:41 UTC, JarrodMFlesch commented
@andershermansen I think this is a very welcome improvement 😃

2024-07-25 13:48 UTC, andershermansen commented
@JarrodMFlesch Great! I’m on leave for the rest of this week, will pick this up and implement the rest next week.

2024-07-30 10:42 UTC, andershermansen commented
@JarrodMFlesch This is now ready for review. The lint error is in a file I have changed, but it's not my change. All other tests are green and I added test case for the new feature.

2024-08-05 18:27 UTC, andershermansen commented
@JarrodMFlesch Did you (or anybody else in payload team) had a chance to take a look?
I merged in latest beta branch now, the lint error is gone as it was fixed in another merged PR. But live-preview test broke. I think it's a flaky test, passes fine locally.

2024-08-05 18:34 UTC, andershermansen commented
Maybe I can interest you with some more screenshots ;)

From dev fields

**Before:**
![admin group fields before](https://github.com/user-attachments/assets/2b829c79-ef81-4d28-9bc2-2fd0dad635ef)

**After:**
![admin group fields after 1](https://github.com/user-attachments/assets/ec4e9e71-55d0-4248-b835-85918344932d)
![admin group fields after 2](https://github.com/user-attachments/assets/d843856a-b1d1-49c3-abf1-cea00a76a1cc)

2024-08-20 19:49 UTC, linobino1 commented
Maybe `|` instead of `>` would be a bit more clear in the columns select toolbar?

2024-08-20 20:14 UTC, andershermansen commented
> Maybe `|` instead of `>` would be a bit more clear in the columns select toolbar?

I think the `>` looks better and is more clear. Also consistent with how the filters is implemented.
Here is how it looks with the `|`
<img width="1185" alt="Skjermbilde 2024-08-20 kl  22 14 06" src="https://github.com/user-attachments/assets/696dc578-9957-428c-a818-6cb4d8de3182">

2024-10-30 07:15 UTC, devj3ns commented
That's a great addition, thanks @andershermansen! I hope this gets reviewed and merged soon :)

2025-02-11 18:48 UTC, sfivash commented
I came here looking for a way to display individual grouped columns.  I hope this feature gets reviewed and merged in.

2025-05-13 15:13 UTC, PatrikKozak commented
Hey @andershermansen! Thanks for your patience with this one and apologies for the delayed review.

I'll be reviewing this myself and helping get this awesome improvement to the finish line!

2025-05-15 17:56 UTC, jacobsfletch commented on packages/payload/src/utilities/flattenTopLevelFields.ts
> +function flattenFields<TField extends ClientField | Field>({
Modifying args here would be considered a breaking change. This function exported from `payload` and used extensively throughout the Payload universe. Modifying the behavior of this function, too, should be done with great caution.

2025-05-15 17:57 UTC, jacobsfletch commented on test/admin/e2e/list-view/e2e.spec.ts
> +    const openColumnControls = async () => {
There is likely a helper function for this already in `test/helpers/e2e`, and if not, this should go there.

2025-05-15 17:58 UTC, jacobsfletch commented on test/admin/e2e/list-view/e2e.spec.ts
> +    test('should allow sorting by nested field within group in separate column', async () => {
We should add an explicit test in addition to this one that ensures the group columns are rendered top level. This test is specific for the sorting behavior.

2025-05-21 19:21 UTC, DanRibbens requested changes
Just one suggestion for this

2025-05-21 19:21 UTC, DanRibbens commented on packages/payload/src/utilities/flattenTopLevelFields.ts
> +  extractFieldsToTopFromGroupFields?: boolean
I'd make this arg name more generic and include tabs with names.

`moveSubFieldsToTop` or some other name.

2025-05-21 20:23 UTC, DanRibbens approved these changes

2025-05-21 20:25 UTC, merged