feat(translations): add danish translations
payloadcms/payload pull request #7809
Opened 2024-08-22 09:24 UTC by mykz

## Description

Added Danish (da-DK) translations for Beta

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2024-09-01 23:08 UTC, AlessioGr requested changes

2024-09-01 23:08 UTC, AlessioGr commented on packages/translations/src/types.ts
> +  | 'da-DK'
needs to be 'da'

2024-09-01 23:08 UTC, AlessioGr commented on packages/translations/src/languages/da.ts
> +  dateFNSKey: 'da-DK',
needs to be 'da'

2024-09-02 04:01 UTC, mykz commented
Thanks for the review, @AlessioGr. I've made the corrections, so hopefully, it's all good now. 🤞

2024-09-02 04:44 UTC, AlessioGr approved these changes

2024-09-11 07:32 UTC, mykz commented
@AlessioGr Any ideas when this PR might get merged?

2024-09-28 22:13 UTC, merged