Fix/beta/7762
payloadcms/payload pull request #7828
Opened 2024-08-23 06:25 UTC by yobottehg

## Description

This PR add more resilience to the payload preferences update. Previously it was possible that if something goes wrong in an preferences update that multiple user preferences would exist for the same entry e.g "locale". This then has unforeseeable consequences throughout the whole application as it's unclear which of these entries will be used and updated.

This caused the following issue: #7762 

This PR also adds an CLI command to cleanup the user preferences table as there is currently no way to recover an affected Payload instance from this behaviour.

- [ ] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [ ] Chore (non-breaking change which does not add functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to the [templates](https://github.com/payloadcms/payload/tree/main/templates) directory (does not affect core functionality)
- [ ] Change to the [examples](https://github.com/payloadcms/payload/tree/main/examples) directory (does not affect core functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2024-08-28 20:45 UTC, JarrodMFlesch commented
@yobottehg I like this, I am not sure we need to keep the remove:preferences script though. Since users could write their own scripts using payload to do that.

2024-08-29 13:35 UTC, DanRibbens requested changes
I don't think this should be necessary and by doing a count you're making extra trips to the DB and awaiting it.

The reason I had optimistically called updateOne was because user preferences can be updated very often for the same keys so this optimization was a substitute for not having `upsert` on our db adapters.

I'd like to avoid making two queries when somebody is simply toggling columns in the list view or collapsing/expanding blocks while editing a document. 

I propose we do three things:
1. ~Solve the issue by adding a sort to the preferences findOne `sort: '-createdAt'` will ensure you always retrieve the newest item even if there is somehow a duplicate.~ EDIT: findOne doesn't support `sort` in our adapter, have to change to `find` with `limit: 1` which is the same thing.
2. Add `sort: '-createdAt'` to the updateOne, since if there are two and we update the older doc, it'll never be read.
3. In the `update` our `catch` after failing to updateOne, we add an `if` statement conditionally the error is an instance of NotFound, then call create. Otherwise it was some other error and we could call `delete` on the same `filter` and try to `create` again.
4. Remove the `await` calls, making this a optimistic update since we never return the db result anyways. This could cut down on race conditions.

2024-09-06 03:52 UTC, paulpopus commented
Closing this PR as we'll work on a new one

2024-09-06 03:52 UTC, closed without merging

2024-09-06 20:14 UTC, DanRibbens commented
Link to replacement PR: https://github.com/payloadcms/payload/pull/8100