feat: allows fields to be collapsed in the version view diff
payloadcms/payload pull request #8054
Opened 2024-09-04 00:38 UTC by franciscolourenco

## Description

Allows some fields to be collapsed in the version diff view. The fields that can be collapsed are the ones which can also be collapsed in the edit view: collapsible, group, arrays and blocks.

This is a draft. Open questions:
- [ ] Is this design ok?
- [ ] Do we want to have the left gutters that were commented out in v3?

- [x] I have read and understand the [CONTRIBUTING.md](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md) document in this repository.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Existing test suite passes locally with my changes
- [ ] I have made corresponding changes to the documentation

2024-09-04 10:42 UTC, franciscolourenco commented
@tsemachh I actually halfway into implementing 2. (rich text rendering in the diff view). Have you started on it already?

Also you might be interested in [this one](https://github.com/payloadcms/payload/pull/7724) too. It was implemented in v2 , but shouldn't be too hard to port to v3.

2024-09-05 08:25 UTC, franciscolourenco commented on packages/next/src/views/Version/RenderFieldsToDiff/FieldDiffCollapser/index.tsx
> +const FieldDiffCollapser: React.FC<Props> = ({ children, initCollapsed = false, label }) => {
Named this component "Collapser" to minimize confusion with the Collapsible field. This component can be used in multiple field components, including the Collapsible field component.

2024-09-05 08:26 UTC, franciscolourenco commented on packages/next/src/views/Version/RenderFieldsToDiff/fields/Collapsible/index.tsx
Added this component to distinguish from other nested fields who shouldn't be collapsible, namely row fields.

2024-09-05 08:30 UTC, franciscolourenco commented on packages/next/src/views/Version/RenderFieldsToDiff/index.tsx
> +              <Component
Not sure if there was a reason for the Nested component to be "fixed" here. I think we can just render the mapped component here, assuming that every nested field has a mapped component. Needed this to render the Nested or Collapsible component depending on the field.

2024-09-05 13:39 UTC, tylandavis commented
Regarding the design, I think the one thing missing here is some sort of indication that a collapsed group has changes or not. perhaps highlighting the group when collapsed to show it has diffed children would be an improvement.

2024-09-05 15:08 UTC, franciscolourenco commented
@tylandavis what about something like this? 


https://github.com/user-attachments/assets/16faa8fc-154c-42fc-b877-94d2422006e6

2024-09-30 12:26 UTC, franciscolourenco commented
@tsemachh what do you think of the current state. Did you have something else in mind?

2024-09-30 13:23 UTC, tsemachh commented
@franciscolourenco It's taking forever to review the PR , I think we need to move forward with it , 
What I see in the video is a good progress.
I will be very happy to see the rich text diff which is the main issue left
(Not mentioning my PR of show modified fields which no one looked at it for few weeks)

2024-09-30 13:29 UTC, franciscolourenco commented
Thanks for the input @tsemachh! I actually meant to tag @tylandavis, sorry.

2024-10-16 15:31 UTC, franciscolourenco commented
@tylandavis makes sense. Just to confirm, 
1. For the calculation of the number, should we use only direct children or take into account all fields even if nested deep? 
2. If we go with the nested approach, if a collapsible/array/blocks/group field has other fields with changes inside, would you count that the collapsible/array/blocks/group itself as a changed field, or only consider it's children?

2024-12-15 05:34 UTC, franciscolourenco commented
Still relevant, will fix merge conflicts soon.

2025-01-17 17:13 UTC, DanRibbens requested changes
Looks like something in our lint config is mad about the changes to translateText.ts which could go into another PR. I would revert that change here and then we can finally get this merged. Great work on the feature with excellent test coverage!

2025-01-17 17:13 UTC, DanRibbens commented on packages/next/src/views/Version/RenderFieldsToDiff/utilities/getFieldsForRowComparison.ts
> +      // {
Need a little cleanup here?

2025-01-17 17:13 UTC, DanRibbens commented on packages/translations/scripts/translateNewKeys/translateText.ts
> +const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))
This is unrelated to the rest of the PR. We usually try and make smaller PRs for such changes.

2025-01-20 09:25 UTC, franciscolourenco commented on packages/next/src/views/Version/RenderFieldsToDiff/utilities/getFieldsForRowComparison.ts
> +      // {
@DanRibbens thank you for the review! 🙏 

I had the same reaction when I saw this code which I extracted from the [Iterable/index.tsx](https://github.com/payloadcms/payload/blob/ef4b8d9b00d6f7de58a6a0f536100fa1ee66dfd6/packages/next/src/views/Version/RenderFieldsToDiff/fields/Iterable/index.tsx#L52-L56) component. It looked like it could have been a leftover, but then I though that it could have been left intentionally to inform the reader on the shape of blocks data. 

That being said, since we both had the same initial reaction I will remove it.

2025-01-24 15:08 UTC, DanRibbens approved these changes
Good job on the changes!

2025-01-24 15:08 UTC, DanRibbens approved these changes
Good job on the changes!

2025-01-24 18:32 UTC, merged