fix(ui): CodeBlock adjusts its height to its content dynamically. Scrolling over the container is not prevented.
payloadcms/payload pull request #8209
Opened 2024-09-13 18:11 UTC by GermanJablo

Closes #8051.

(Writing description right now...)

2024-09-15 16:44 UTC, AlessioGr requested changes
![CleanShot 2024-09-15 at 09 42 38@2x](https://github.com/user-attachments/assets/d7805229-ceaf-44b5-bc31-e43caf907e1e)

For large code blocks, we do want there to be a scrollbar and a maximum default height, as long as the focus isn't captured as aggressively as before.
Now, there are no scrollbars at all (screenshot is from the Code collection in the fields test suite)

2024-09-17 06:38 UTC, AlessioGr commented
> and a nested scroll can create some pretty annoying scrolling "traps". Auto-scrolling an inner element scrolls the outermost element.
> Which element is scrolled depends on the mouse position. A user who has to scroll a lot on a long element is likely to move the mouse and enter another area in the process scrolling an element he didn't want to scroll.

We could still explore _only_ locking the scroll if the editor is clicked, or if the mouse is hovering over it for a significant amount of time (Saw https://github.com/payloadcms/payload/pull/8241 being opened). This would alleviate that.

But generally I'd be completely fine with code fields inside of lexical blocks not having a maximum height! If they are too long, the user has the option of collapsing the block.

The screenshot however is from the normal document view outside of lexical - so just a normal standalone Code field. I feel like it might be a good idea to keep the maximum height there, as you cannot collapse them if they're not usually that useful to look at and consume too much space.
Same could be said for rich text fields though. Or Tables.

I 100% agree one single scroll is easier to understand, but I also feel like code fields could get pretty long and can often take up too much space you'd want for other stuff

2024-09-17 13:09 UTC, GermanJablo commented
Outside of Lexical you usually have a scrollable container as well.
For example, a codeBlock in a blog post. The blog is already scrollable.
The only case where it makes sense **to me** to have a max height is when there is no scrollable container.
In the case of the codeBlock, this would be if you are creating an IDE where the codeBlock is the container (it takes up the entire viewport).
In the case of the table, this would be if you are creating something like G. Sheets where the table is the container (it takes up the entire viewport).

In other words, very extraordinary exceptions.

2024-09-17 19:54 UTC, AlessioGr approved these changes

2024-09-17 19:55 UTC, merged