feat(payload, ui): add allowEdit config to the admin of the relationship field
payloadcms/payload pull request #8398
Opened 2024-09-24 21:50 UTC by GermanJablo

This PR adds a new property `allowEdit` to the admin of the relationship field. It is very similar to the existing `allowCreate`, only in this case it hides the edit icon:

<img width="796" alt="image" src="https://github.com/user-attachments/assets/bbe79bb2-db06-4ec4-b023-2f1c53330fcb">

2024-09-25 21:32 UTC, GermanJablo commented
This is done @DanRibbens

2024-09-26 03:24 UTC, DanRibbens requested changes
I'd like to have the tests changed so the assertions are retryable. Apart from that everything looks good!

2024-09-26 03:24 UTC, DanRibbens commented on test/fields/collections/Relationship/e2e.spec.ts
> +    expect(count1).toEqual(1)
We typically use the `.toHaveCount()` assertion which let's you skip assigning the count variable. The main thing you lose here is that this isn't retryable. https://playwright.dev/docs/test-assertions#auto-retrying-assertions

2024-09-27 13:19 UTC, DanRibbens approved these changes

2024-09-27 13:22 UTC, merged