chore(docs): add note about condition with custom field component
payloadcms/payload pull request #8440
Opened 2024-09-27 00:25 UTC by r1tsuu

Adds a note about `admin.condition` when using custom field component.

2024-09-27 00:51 UTC, jacobsfletch commented
This could likely be wired up so that the custom wrapper is unnecessary. Especially with https://github.com/payloadcms/payload/pull/8364. We should explore this further.

2024-10-24 19:20 UTC, DanRibbens approved these changes

2024-10-24 19:21 UTC, DanRibbens requested changes
whoops! I approved before I saw this comment https://github.com/payloadcms/payload/pull/8440#issuecomment-2378196596.
That would be nice.

Should we close this PR?

2024-10-24 21:04 UTC, r1tsuu commented
Likely

2024-10-24 21:04 UTC, closed without merging