feat: add localized indicator to field label
payloadcms/payload pull request #8602
Opened 2024-10-08 17:33 UTC by JessChowdhury

On any localized field, appends `locale` on the end of the label.

2024-10-09 16:11 UTC, DanRibbens requested changes
I am looking at the `test/localizations` and clicking around. It doesn't appear that all the labels are impacted by this change.
Should a localized block show the current locale?
![image](https://github.com/user-attachments/assets/a11089e5-6fa9-45df-88e9-ca0175bc7b93)

2024-10-09 18:11 UTC, JessChowdhury commented on packages/ui/src/fields/FieldLabel/index.tsx
> +          : props?.field && 'required' in props.field && (props.field?.required) // type assertion needed for `group` fields
Ah nope, this happened when I saved the file - reverted.

2024-10-09 18:11 UTC, JessChowdhury commented
> I am looking at the `test/localizations` and clicking around. It doesn't appear that all the labels are impacted by this change. Should a localized block show the current locale? ![image](https://private-user-images.githubusercontent.com/6434612/375042811-a11089e5-6fa9-45df-88e9-ca0175bc7b93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTY3ODAsIm5iZiI6MTcyODQ5NjQ4MCwicGF0aCI6Ii82NDM0NjEyLzM3NTA0MjgxMS1hMTEwODllNS02ZmE5LTQ1ZGYtODhlOS1jYTAxNzViYzdiOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMTc1NDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE4YzZlMWUwNmRlNzgyZjM3YWQyNWU1MDA2YTdjZTJlMzI5NWI4ZGJiY2Q5MzUyMzJmMTZlZTM4ZWUyYTVkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Dm8BjPCY4y3QDiOp5m3B02DS1CHug0iIGoRd7DOEdiw)

Yes, will correct this.

2024-10-09 18:22 UTC, DanRibbens commented on packages/ui/src/fields/FieldLabel/index.tsx
> +          : props?.field && 'required' in props.field && (props.field?.required) // type assertion needed for `group` fields
If eslint removed it and this builds, I'd say we can drop it and the comment.

2024-10-10 21:01 UTC, DanRibbens commented
I need clarification on this. I was expecting that the label at the top most localized field would be the one to show the indicator.
Now I see on your branch we are showing the `text` field has the label `en`. Instead though I was expecting that the Content at the top level would have the indicator because that is the level at which we have added localization.

![image](https://github.com/user-attachments/assets/29e5d8c3-fc3c-469e-a2a3-62fdc261909f)

2024-10-10 21:40 UTC, JessChowdhury commented
> I need clarification on this. I was expecting that the label at the top most localized field would be the one to show the indicator. Now I see on your branch we are showing the `text` field has the label `en`. Instead though I was expecting that the Content at the top level would have the indicator because that is the level at which we have added localization.
> 
> ![image](https://private-user-images.githubusercontent.com/6434612/375543661-29e5d8c3-fc3c-469e-a2a3-62fdc261909f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1OTY2MDgsIm5iZiI6MTcyODU5NjMwOCwicGF0aCI6Ii82NDM0NjEyLzM3NTU0MzY2MS0yOWU1ZDhjMy1mYzNjLTQ2OWUtYTJhMy02MmZkYzI2MTkwOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMjEzODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlkNzFlODU1ZTVjYzUwMjc3YTg2ZTc5OTlhZWQ4MDlmOTU5NTE3NDM3Y2Q0MDlmOGYxOGZhYzBjNWVlOTg2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vRiLqNrv36o1sDrUfI3j8dMKCBy_akBFUqvQIHsbr9c)

Ah okay we might need to talk through this - I thought we have situations where the block could be localized but have a field with `localized: false` within in, in which case you would want to know on a field by field basis. Might be a better way to do this...

2024-10-11 12:44 UTC, DanRibbens commented
> I thought we have situations where the block could be localized but have a field with localized: false within

No, we just need to have the indicator shown at the label for any field that has `localization: true` and then any subfields need to be ignored. Even if the fields had `localized: true` or `false` nested inside another `localized: true` it should be ignored.

2024-10-11 19:03 UTC, JessChowdhury commented
> No, we just need to have the indicator shown at the label for any field that has `localization: true` and then any subfields need to be ignored.

Gotcha - I have updated it so the indicator only appends fields that have `localization: true`.

2024-10-17 19:47 UTC, DanRibbens requested changes
Well shit, sorry I missed in the indicator design in the earier reviews.

Also it looks like we're missing the indicator for checkbox field types.

One more round!

2024-10-17 19:47 UTC, DanRibbens commented on packages/ui/src/fields/FieldLabel/index.tsx
> +        {localized && <span className="localized">{code}</span>}
Looks like were going with en dash, also the code should only be used when there isn't a `locale.label`

2024-10-23 19:05 UTC, denolfe approved these changes

2024-10-23 19:06 UTC, merged