feat: conditional tabs
payloadcms/payload pull request #8720
Opened 2024-10-15 20:14 UTC by paulpopus

2025-01-02 08:55 UTC, a-stein commented
Any estimation when this will be merged?

2025-02-27 15:07 UTC, r1tsuu reviewed
Just some unused imports

2025-02-28 13:58 UTC, JarrodMFlesch requested changes

2025-02-28 13:58 UTC, JarrodMFlesch commented on packages/payload/src/errors/DuplicateTabsIds.ts
> +}
I dont see this code being used anywhere

2025-03-10 18:58 UTC, paulpopus commented on packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
> +      }
I changed it to always be the ID

2025-03-12 03:55 UTC, JarrodMFlesch commented on packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
> +          : true
```suggestion
      const tabPassesCondition =
        passesCondition && typeof tab.admin?.condition === 'function'
          ? tab.admin.condition(fullData, data, { blockData, path: pathSegments, user: req.user })
          : passesCondition
```

2025-03-12 03:57 UTC, JarrodMFlesch requested changes

2025-03-12 03:57 UTC, JarrodMFlesch commented on packages/ui/src/forms/fieldSchemasToFormState/addFieldStatePromise.ts
> +          : true
If there is no admin.condition or passesCondition is false, it will always be true here.

```suggestion
      const tabPassesCondition =
        passesCondition && typeof tab.admin?.condition === 'function'
          ? tab.admin.condition(fullData, data, { blockData, path: pathSegments, user: req.user })
          : passesCondition
```

2025-03-12 18:40 UTC, JarrodMFlesch submitted a review, later dismissed

2025-03-13 13:24 UTC, JarrodMFlesch approved these changes

2025-03-13 13:32 UTC, merged