chore(richtext-lexical): add noImplicitAny to the richtext-lexical package
payloadcms/payload pull request #8763
Opened 2024-10-17 18:12 UTC by GermanJablo

2024-10-18 03:58 UTC, AlessioGr requested changes

2024-10-18 03:58 UTC, AlessioGr commented on packages/richtext-lexical/src/features/upload/client/drawer/index.tsx
> +    ({ collectionSlug, docID }: { collectionSlug: string; docID: string }) => {
docID needs to be string | number due to postgres

2024-11-15 18:15 UTC, GermanJablo commented
I don't know what's going on with the failing test.
I've already tried clearing the cache, and retrying several times.
only happens in the localization folder

2024-11-21 01:34 UTC, AlessioGr approved these changes

2024-11-21 01:46 UTC, merged