feat: add support for public custom views in admin and fix issues with notfound
payloadcms/payload pull request #8820
Opened 2024-10-21 22:11 UTC by paulpopus

This PR aims to fix a few issues with the notFound page so it matches v2 behaviour:
- Non authorised users should always be redirected to the login page regardless if not found or valid URL
  - Previously notFound would render for non users too potentially exposing valid but protected routes and creating a confusing workflow as the UI was being rendered as well
- Custom views have the option to be publicly accessible
  - adds a new config for custom views `public` that controls this behaviour
  - in our `admin` test suite, the `/admin/custom-view` is accessible to non users but `/admin/custom-view/nested-view` is not 
- Fixes https://github.com/payloadcms/payload/issues/8716

2024-10-21 22:31 UTC, jmikrut commented on packages/next/src/views/Root/index.tsx
> +  dbHasUser = await initPageResult?.req.payload.db
i do not know that i like this here - this is akin to the `init` operation, right? isn't that being run somewhere else already?

2024-10-22 14:37 UTC, DanRibbens requested changes
I can see a lot of power and reusability in making an `access` function that we call before serving the view. That would reduce the effort of gating views to only certain users while also allowing your use case of public access.
What do you think?

2024-10-22 14:37 UTC, DanRibbens commented on docs/admin/views.mdx
> +| **`public`**       | When true, this path will be accessible to non logged in users allowing you to control access. Combine it with `exact: true` if you want nested paths to not be public. |
Is this the right way or should we make an access function specific to the view?

2024-10-25 19:12 UTC, DanRibbens approved these changes

2024-10-30 17:29 UTC, merged