feat: add connection string flag `--dbUri` to main command
payloadcms/payload pull request #9084
Opened 2024-11-08 13:09 UTC by maneike

### What?
I have implemented  `--dbUri` flag which accepts a connection string.
### Why?
In CI/CD environments it's very hard to go through `create-payload-app` process without interfering with the prompt interactions.  
### How?
A simple check for `--dbUri` in `packages/create-payload-app/src/lib/select-db.ts` before prompting for connection string.

Example usage:
`create-payload-app --dbUri postgresql://user:password@localhost:5432/postgres`

2024-11-08 13:34 UTC, maneike commented
Would it be possible to introduce it to beta too?

2024-11-08 21:16 UTC, DanRibbens requested changes
Looks good besides the property is not formatted as I would expect it.

> Would it be possible to introduce it to beta too?

This is a good call!

2024-11-09 13:56 UTC, maneike commented on packages/create-payload-app/src/types.ts
> +  '--dbUri': StringConstructor
Done! 🫡

2024-11-12 18:26 UTC, maneike commented
> Looks good besides the property is not formatted as I would expect it.
> 
> > Would it be possible to introduce it to beta too?
> 
> This is a good call!

@DanRibbens should I just change base to `beta`?

2024-11-12 20:33 UTC, DanRibbens commented
> @DanRibbens should I just change the base branch to `beta`?

I'm not sure because a lot has changed between main and beta. You can try and see and if it has conflicts.

I recommend branching from beta and doing a cherry-pick of these commits. You might have to resolve a few conflicts.

2024-11-13 11:06 UTC, closed without merging