feat(richtext-lexical): add TextStateFeature (allows applying styles such as color and background color to text)
payloadcms/payload pull request #9667
Opened 2024-12-02 17:05 UTC by GermanJablo

Originally this PR was going to introduce a `TextColorFeature`, but it ended up becoming a more general-purpose `TextStateFeature`.

## Example of use:
```ts
import { defaultColors, TextStateFeature } from '@payloadcms/richtext-lexical'

TextStateFeature({
  // prettier-ignore
  state: {
    color: {
      ...defaultColors,
      // fancy gradients!
      galaxy: { label: 'Galaxy', css: { background: 'linear-gradient(to right, #0000ff, #ff0000)', color: 'white' } },
      sunset: { label: 'Sunset', css: { background: 'linear-gradient(to top, #ff5f6d, #6a3093)' } },
    },
    // You can have both colored and underlined text at the same time. 
    // If you don't want that, you should group them within the same key.
    // (just like I did with defaultColors and my fancy gradients)
    underline: {
      'solid': { label: 'Solid', css: { 'text-decoration': 'underline', 'text-underline-offset': '4px' } },
       // You'll probably want to use the CSS light-dark() utility.
      'yellow-dashed': { label: 'Yellow Dashed', css: { 'text-decoration': 'underline dashed', 'text-decoration-color': 'light-dark(#EAB308,yellow)', 'text-underline-offset': '4px' } },
    },
  },
}),

```

Which will result in the following:

![image](https://github.com/user-attachments/assets/ed29b30b-8efd-4265-a1b9-125c97ac5fce)

## Challenges & Considerations
Adding colors or styles in general to the Lexical editor is not as simple as it seems.

1. **Extending TextNode isn't ideal**
    - While possible, it's verbose, error-prone, and not composable. If multiple features extend the same node, conflicts arise.
    - That’s why we collaborated with the Lexical team to introduce [the new State API](https://lexical.dev/docs/concepts/node-replacement) ([PR](https://github.com/facebook/lexical/pull/7117)).
2. **Issues with patchStyles**
    - Some community plugins use `patchStyles`, but storing CSS in the editor’s JSON has drawbacks:
      - Style adaptability: Users may want different styles per scenario (dark/light mode, mobile/web, etc.).
      - Migration challenges: Hardcoded colors (e.g., #FF0000) make updates difficult. Using tokens (e.g., "red") allows flexibility.
      - Larger JSON footprint increases DB size.
3. **Managing overlapping styles**
    - Some users may want both text and background colors on the same node, while others may prefer mutual exclusivity.
    - This approach allows either:
        - Using a single "color" state (e.g., "bg-red" + "text-red").
        - Defining separate "bg-color" and "text-color" states for independent styling.
4. **Good light and dark modes by default**
    - Many major editors (Google Docs, OneNote, Word) treat dark mode as an afterthought, leading to poor UX.
    - We provide a well-balanced default palette that looks great in both themes, serving as a strong foundation for customization.
5. **Feature name. Why TextState?**
    - Other names considered were `TextFormatFeature` and `TextStylesFeature`. The term `format` in Lexical and Payload is already used to refer to something else (italic, bold, etc.). The term `style` could be misleading since it is never attached to the editorState.
    - State seems appropriate because:
      - Lexical's new state API is used under the hood.
      - Perhaps in the future we'll want to make state features for other nodes, such as `ElementStateFeature` or `RootStateFeature`.

Note: There's a bug in Lexical's `forEachSelectedTextNode`. When the selection includes a textNode partially on the left, all state for that node is removed instead of splitting it along the selection edge.

2025-03-25 17:58 UTC, wellitongervickas commented
following

2025-04-26 03:43 UTC, rickgrade3 commented
so good

2025-04-30 15:36 UTC, wellitongervickas commented
So far so good, just saw the last commit! 🤭

2025-05-03 18:24 UTC, chaotic-justice commented
will this also enable users to pick from a range of px font sizes for text content?

2025-05-13 19:47 UTC, AdrianMaj commented
Hey, when we can expect it to be merged? Looks amazing! 🔥

2025-05-15 12:49 UTC, GermanJablo commented
It's pending review by @AlessioGr 
He's been very busy, hopefully very soon!

2025-05-21 17:05 UTC, AlessioGr requested changes

2025-05-21 17:25 UTC, GermanJablo commented on packages/richtext-lexical/package.json
> +    "csstype": "3.1.3",
good catch!

2025-05-21 22:07 UTC, AlessioGr submitted a review, later dismissed

2025-05-21 23:24 UTC, AlessioGr approved these changes

2025-05-21 23:58 UTC, merged

2025-05-22 00:14 UTC, wellitongervickas commented
Wow thanks

2025-06-11 17:55 UTC, drago1520 commented
Does anyone have font sizes and other utilities from Tailwind CSS's design system as options for `TextStateFeature`?

2025-06-11 18:30 UTC, GermanJablo commented
Not really. But it's very easy to do yourself. I made it defaultColors because it required more thought for light/dark mode :)