fix(richtext-lexical): ensure sub-fields have access to full document data
payloadcms/payload pull request #9869
Opened 2024-12-10 18:05 UTC by AlessioGr

2025-01-31 15:52 UTC, DanRibbens requested changes, later dismissed
I think this makes sense from what I'm seeing and doesn't seem too much of a hack. I would like to know if there are ramifications that I'm not seeing.

It needs a test.

2025-01-31 15:52 UTC, DanRibbens commented on packages/ui/src/forms/Form/types.ts
> +  isDocumentForm?: boolean
Could use some jsdocs to help us reason what this flag is later.

2025-02-05 00:42 UTC, jmikrut commented on packages/richtext-lexical/src/utilities/buildInitialState.ts
> +        fullDataOverride: context.documentData,
I don't love the name of this property. It feels like `documentData` above is accurate, but `fullDataOverride` kind of throws me for a loop.

2025-02-05 00:43 UTC, jmikrut commented on packages/richtext-lexical/src/features/blocks/client/component/index.tsx
> +        fullFormStateOverride: deepCopyObjectSimpleWithoutReactComponents(parentDocumentFields),
I also do not love this name. Feels like this could be called `parentDocFormState` or similar. Or `topLevelDoc`?

2025-02-05 00:45 UTC, jmikrut commented
Quick thoughts from my side:

1. You are _replacing_ `data` which is a current argument, representing the specific `block` of a Lexical field. This could be unexpected for those that already have Lexical blocks being used and treat the `data` as the `block` data. This should be done lightly or maybe even as an opt-in pattern.
2. Instead of replacing `data`, could we provide another optional argument called `parentData` or `topLevelData` or similar, which is always defined, but it is either what is now `data` - - OR, in the case of being inside a Lexical block, it would be the parent document's form state data?

I prefer option 2 here. It would be non-breaking and simply be a way to expose more, without losing what we have. 

Thoughts?

2025-02-06 06:10 UTC, AlessioGr commented on packages/payload/src/fields/config/types.ts
> +  blockData?: JsonObject | undefined
Is this included for field.create and field.update access control? If not, either add it or document it in the jsdocs

2025-02-06 18:49 UTC, jmikrut approved these changes

2025-02-06 18:49 UTC, merged

2025-05-20 09:45 UTC, bratvanov commented
Hey @AlessioGr I just wanted to flag #11399 as `useDocumentForm` is still not working in Live Preview. I would greatly appreciate some insight into this.