refactor: deduplicate and abstract SQL schema building
payloadcms/payload pull request #9987
Opened 2024-12-15 09:03 UTC by r1tsuu

### What?
Abstracts SQL schema building, significantly reducing code duplication for SQLite / Postgres

db-sqlite lines count From:
```sh
 wc -l **/*.ts
      62 src/connect.ts
      32 src/countDistinct.ts
       9 src/createJSONQuery/convertPathToJSONTraversal.ts
      86 src/createJSONQuery/index.ts
      15 src/defaultSnapshot.ts
       6 src/deleteWhere.ts
      21 src/dropDatabase.ts
      15 src/execute.ts
     178 src/index.ts
     139 src/init.ts
      19 src/insert.ts
      19 src/requireDrizzleKit.ts
     544 src/schema/build.ts
      27 src/schema/createIndex.ts
      38 src/schema/getIDColumn.ts
      13 src/schema/idToUUID.ts
      28 src/schema/setColumnID.ts
     787 src/schema/traverseFields.ts
      18 src/schema/withDefault.ts
     248 src/types.ts
    2304 total
```

To:
```sh
wc -l **/*.ts
      62 src/connect.ts
      32 src/countDistinct.ts
       9 src/createJSONQuery/convertPathToJSONTraversal.ts
      86 src/createJSONQuery/index.ts
      15 src/defaultSnapshot.ts
       6 src/deleteWhere.ts
      21 src/dropDatabase.ts
      15 src/execute.ts
     180 src/index.ts
      39 src/init.ts
      19 src/insert.ts
      19 src/requireDrizzleKit.ts
     149 src/schema/buildDrizzleTable.ts
      32 src/schema/setColumnID.ts
     258 src/types.ts
     942 total
```

2024-12-15 12:00 UTC, DanRibbens requested changes
This is very exciting to me. I wanted to do this when we first built SQLite and opted to speed past it. I love that you cleaned up our tech debt here. 

I have a few questions after reviewing from mobile.

2024-12-15 12:12 UTC, r1tsuu commented on packages/drizzle/src/types.ts
> +export type RawRelation =
Perhaps SourceRelation etc? Since that "raw" schema is fully JSON serializable

2024-12-16 05:57 UTC, r1tsuu commented on packages/drizzle/src/schema/withDefault.ts
> +      default: `SRID=4326;POINT(${field.defaultValue[0]} ${field.defaultValue[1]})`,
Abstracted that part directly to `db-sqlite/buildDrizzleTable`.

2024-12-16 05:57 UTC, r1tsuu commented on packages/db-sqlite/src/init.ts
> +      rawRelations: this.rawRelations[tableName],
Changed

2024-12-16 14:15 UTC, DanRibbens commented on packages/drizzle/src/types.ts
> +export type RawRelation =
With the extra jsdocs, I think raw is fine. Thanks for adding those!

2024-12-16 14:17 UTC, DanRibbens approved these changes
Great work!

2024-12-16 14:23 UTC, r1tsuu commented
I'll do some extra migrations regression testing just in case and then merge

2024-12-16 15:17 UTC, r1tsuu commented
With the website template when updated to `3.7.1-canary.2ce70a3` I didn't get schema changes.

2024-12-16 15:17 UTC, merged